### ISSUE TITLE
feat: Settings system

### ISSUE THREAD

**Issue by TomDotBat** [TomDotBat/pixel-ui#16]
Add a menu which you can configure client-side UI settings from, and add functions that make it easy for developers to implement.

**Comment by bludotbat** [comment]
pixel settings could work for this with some refactoring

**Comment by garryspins** [comment]
> pixel settings could work for this with some refactoring

as long as im credited, sure

**Comment by TomDotBat** [comment]
I'm already working on my own solution, so no need.
