### ISSUE TITLE
PIXEL.DrawImgur stop working

### ISSUE THREAD

**Issue by victornishtyakov** [TomDotBat/pixel-ui#45]
All images stop download to the folder data/pixel

**Comment by TomDotBat** [comment]
Please elaborate, providing screenshots if possible.

**Comment by victornishtyakov** [comment]
https://i.imgur.com/ClmLQ0l.png

**Comment by victornishtyakov** [comment]
Is this problem just me?

**Comment by TomDotBat** [comment]
Is this issue still present on the [latest release](https://github.com/TomDotBat/pixel-ui/releases/latest)?

**Comment by TomDotBat** [comment]
#48

**Comment by victornishtyakov** [comment]
Very strange, but the pictures are still not loading. Folders are created, but pictures are not loaded. When opening the menu, images rotate and do not load. I downloaded the latest release.
