### ISSUE TITLE
FindMetaTable seems to be not working in cl_color.lua

### ISSUE THREAD

**Issue by Quphoria** [TomDotBat/pixel-ui#53]
I'm playing on a server which has an addon which uses Pixel UI
I'm getting script errors from cl_color.lua

```lua
[_mutui] addons/_mutui/lua/pixelui/core/cl_color.lua:154: attempt to index local 'colorMeta' (a nil value)
    1. unknown - addons/_mutui/lua/pixelui/core/cl_color.lua:154
        2. include - [C]:-1
            3. LoadDirectory - addons/_mutui/lua/autorun/sh_pixelui_loader.lua:30
                4. LoadDirectoryRecursive - addons/_mutui/lua/autorun/sh_pixelui_loader.lua:47
                    5. LoadDirectoryRecursive - addons/_mutui/lua/autorun/sh_pixelui_loader.lua:49
                        6. unknown - addons/_mutui/lua/autorun/sh_pixelui_loader.lua:53
```

Which seems to indicate an issue with the following code in cl_color.lua (Line 153)
```lua
local colorMeta = FindMetaTable("Color")
colorMeta.Copy = PIXEL.CopyColor
colorMeta.IsLight = PIXEL.IsColorLight
colorMeta.EqualTo = PIXEL.IsColorEqualTo
```

It seems that `FindMetaTable("Color")` is returning nil instead of a table.

If you have any idea how to fix this, that would be great

**Comment by Lythium4848** [comment]
@Quphoria is your server running the latest version?

**Comment by Quphoria** [comment]
It looks to be

**Comment by Lythium4848** [comment]
I'll look into a fix asap

**Comment by Quphoria** [comment]
Thanks, I believe it was working fine, until I unsubscribed from all my gmod addons and did a fresh install

**Comment by Quphoria** [comment]
I've just managed to get your pixel-f4 menu working, so it is probably a bug with the server, not your code

**Comment by Lythium4848** [comment]
Everything seems to be working on the latest version (240105), if anyone else is having this issue please ensure your server is up to date

**Comment by Quphoria** [comment]
Yeah it was an issue due to an outdated lua/include/init.lua, as there has been a bit added at the top which is what the lua/include/util/color.lua script uses to register the "Color" metatable, without it the "Color" metatable doesn't get registered.
If your gmod server overwrites your init.lua, you need to make sure your server has an up-to-date init.lua as otherwise it will break your client
