### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Kryonite-UserFarm** [TomDotBat/pixel-ui#54]
empty f4 and spammed error in console

[pixel-ui-1.3.1] addons/pixel-ui-1.3.1/lua/pixelui/core/cl_color.lua:145: attempt to call method 'Lerp' (a nil value)
  1. LerpColor - addons/pixel-ui-1.3.1/lua/pixelui/core/cl_color.lua:145
   2. unknown - addons/pixel-ui-1.3.1/lua/pixelui/elements/cl_button.lua:121 (x3)

**Comment by Lythium4848** [comment]
What version of gmod are you running?
`lua_run print(VERSION)`

**Comment by Kryonite-UserFarm** [comment]
> What version of gmod are you running? `lua_run print(VERSION)`

240123

**Comment by Lythium4848** [comment]
I'll take a look into it in the morning

**Comment by Lythium4848** [comment]
Can you try the solution at the bottom of #53

**Comment by Kryonite-UserFarm** [comment]
> Can you try the solution at the bottom of #53

where do i find init.lua?
